server:
  port: 8086

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://39.106.228.114:3308/main?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    #    password: 2713505690
    #    url: jdbc:mysql://localhost:3306/the_secondary_market?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 20MB    # 单个文件最大大小
      max-request-size: 20MB  # 单次请求最大文件大小
      enabled: true

  application:
    name: the_secondary_market

  #  resources:
  #    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:D:/MyProgram/test/static/
  #  mvc:
  #    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:/server/thesecondmarket/static/
  mvc:
    static-path-pattern: /**

  # 使用thymeleaf缓存
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: com/hananoq/mapper/*.xml

#mybatis log 插件启用
logging:
  level:
    com: debug
